version: "3"
services:
  frontend: 
    container_name: frontend
    image: node:12
    volumes:
    - ../frontend/client:/app
    ports:
    - 3000:3000
    networks:
    - server-net
    working_dir: /app
    command: npm start
    depends_on: 
      - main
    restart: always

  main: 
    container_name: main
    image: node:12
    volumes:
    - .:/app
    ports:
    - 5000:5000
    networks:
    - server-net
    env_file:
    - .env
    working_dir: /app
    command: npm run start:dev
    depends_on: 
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
    - .env
    environment: 
      PG_DATA: /var/lib/postgresql/data
    networks:
      - server-net
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
 
  pgadmin:
    container_name: pgadminc
    depends_on: 
      - postgres
    image: dpage/pgadmin4
    networks:
      - server-net
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - .env
volumes: 
  pgdata:
networks:
  server-net:
    driver: bridge